# Generated by Django 4.2.1 on 2023-08-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomInvite',
            new_name='ServerInvite',
        ),
    ]
