# Generated by Django 4.2.1 on 2023-06-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_good',
            field=models.BooleanField(default=True),
        ),
    ]
