# Generated by Django 4.2.1 on 2023-08-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
