# Generated by Django 4.2.1 on 2023-08-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0002_rename_roominvite_serverinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverinvite',
            name='invited_user',
        ),
    ]
