# Generated by Django 4.2.1 on 2023-08-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0002_server_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='creator',
        ),
    ]
