# Generated by Django 4.2.1 on 2023-08-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0003_remove_room_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=155),
        ),
    ]
