# Generated by Django 4.2.1 on 2023-06-22 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0003_remove_customuser_is_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.SlugField(max_length=100),
        ),
    ]
