# Generated by Django 4.2.1 on 2023-07-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0004_alter_notification_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='desription',
            new_name='description',
        ),
    ]
