# Generated by Django 4.2.1 on 2023-08-07 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0004_remove_serverinvite_room_serverinvite_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinvite',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serverinvite',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viperchat.server'),
        ),
    ]
