# Generated by Django 4.2.1 on 2023-08-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0004_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
