# Generated by Django 4.2.1 on 2023-08-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0005_server_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverpermissionsettings',
            name='masters_create_room',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Allowed', max_length=20),
        ),
        migrations.AddField(
            model_name='serverpermissionsettings',
            name='masters_delete_messages',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Allowed', max_length=20),
        ),
        migrations.AddField(
            model_name='serverpermissionsettings',
            name='masters_delete_user',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Allowed', max_length=20),
        ),
        migrations.AddField(
            model_name='serverpermissionsettings',
            name='masters_send_invitation',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Allowed', max_length=20),
        ),
        migrations.AddField(
            model_name='serverpermissionsettings',
            name='members_create_room',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Allowed', max_length=20),
        ),
        migrations.AddField(
            model_name='serverpermissionsettings',
            name='members_delete_messages',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Allowed', max_length=20),
        ),
        migrations.AddField(
            model_name='serverpermissionsettings',
            name='members_delete_user',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Allowed', max_length=20),
        ),
        migrations.AddField(
            model_name='serverpermissionsettings',
            name='moderators_create_room',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Allowed', max_length=20),
        ),
    ]
