# Generated by Django 4.2.1 on 2023-07-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0005_alter_room_name_alter_room_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
