# Generated by Django 4.2.1 on 2023-08-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0007_rename_masters_send_invitation_to_group_serverpermissionsettings_masters_send_invitation_to_server_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverinvite',
            name='accepted',
        ),
        migrations.AddField(
            model_name='serverinvite',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('accepted', 'accepted'), ('declined', 'declined')], default='waiting', max_length=64),
        ),
    ]
