# Generated by Django 4.2.1 on 2023-08-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0007_alter_server_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'permissions': [('create_room_in_server', 'Can create room in server'), ('send_messages_in_server', 'Can send messages in server')]},
        ),
        migrations.AddField(
            model_name='serverpermissionsettings',
            name='masters_send_messages',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Allowed', max_length=20),
        ),
        migrations.AddField(
            model_name='serverpermissionsettings',
            name='members_send_messages',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Allowed', max_length=20),
        ),
        migrations.AddField(
            model_name='serverpermissionsettings',
            name='moderators_send_messages',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Allowed', max_length=20),
        ),
    ]
