# Generated by Django 4.2.1 on 2023-07-22 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0008_remove_friendrequest_is_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyRoomNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_creator', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_request_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
