# Generated by Django 4.2.1 on 2023-08-02 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0008_alter_server_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
    ]
