# Generated by Django 4.2.1 on 2023-07-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0009_privacyroomnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privacyroomnotification',
            old_name='sender',
            new_name='join_request_sender',
        ),
        migrations.RenameField(
            model_name='privacyroomnotification',
            old_name='receiver',
            new_name='room_creator',
        ),
    ]
