# Generated by Django 4.2.1 on 2023-09-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0009_chat_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_receiver',
        ),
    ]
