# Generated by Django 4.2.1 on 2023-08-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0009_remove_room_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': [('delete_user_from_server', 'Can delete user from server'), ('display_room_data', 'Can see room details')]},
        ),
    ]
