# Generated by Django 4.2.1 on 2023-07-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0010_rename_sender_privacyroomnotification_join_request_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacyroomnotification',
            name='description',
        ),
    ]
