# Generated by Django 4.2.1 on 2023-08-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0010_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'permissions': [('create_room_in_server', 'Can create room in server'), ('send_messages_in_server', 'Can send messages in server'), ('delete_masters_from_server', 'Can delete users in master group'), ('delete_moderators_from_server', 'Can delete users in moderators group'), ('delete_members_from_server', 'Can delete users in members group')]},
        ),
        migrations.AddField(
            model_name='serverpermissionsettings',
            name='delete_masters_from_room',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Allowed', max_length=20),
        ),
        migrations.AddField(
            model_name='serverpermissionsettings',
            name='delete_members_from_room',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Allowed', max_length=20),
        ),
        migrations.AddField(
            model_name='serverpermissionsettings',
            name='delete_moderators_from_room',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Allowed', max_length=20),
        ),
    ]
