# Generated by Django 4.2.1 on 2023-08-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0011_alter_server_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('delete_message_from_server', 'Can delete message from server')]},
        ),
    ]
