# Generated by Django 4.2.1 on 2023-08-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0012_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverpermissionsettings',
            name='delete_masters_from_room',
        ),
        migrations.RemoveField(
            model_name='serverpermissionsettings',
            name='delete_members_from_room',
        ),
        migrations.RemoveField(
            model_name='serverpermissionsettings',
            name='delete_moderators_from_room',
        ),
    ]
