# Generated by Django 4.2.1 on 2023-07-22 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0012_rename_privacyroomnotification_privateroomjoinnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateroomjoinnotification',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viperchat.room'),
        ),
    ]
