# Generated by Django 4.2.1 on 2023-08-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0013_remove_serverpermissionsettings_delete_masters_from_room_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'permissions': [('create_room_in_server', 'Can create room in server'), ('send_messages_in_server', 'Can send messages in server'), ('delete_masters_from_server', 'Can delete users in master group'), ('delete_moderators_from_server', 'Can delete users in moderators group'), ('delete_members_from_server', 'Can delete users in members group'), ('edit_permissions_in_server', 'Can modify groups permissions')]},
        ),
    ]
