# Generated by Django 4.2.1 on 2023-07-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0014_alter_privateroomjoinnotification_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivateRoomJoinNotification',
            new_name='RoomJoinNotification',
        ),
    ]
