# Generated by Django 4.2.1 on 2023-08-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0014_alter_server_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverpermissionsettings',
            old_name='masters_send_invitation',
            new_name='masters_send_invitation_to_group',
        ),
        migrations.RenameField(
            model_name='serverpermissionsettings',
            old_name='members_send_invitation',
            new_name='members_send_invitation_to_group',
        ),
        migrations.RenameField(
            model_name='serverpermissionsettings',
            old_name='moderators_send_invitation',
            new_name='moderators_send_invitation_to_group',
        ),
    ]
