# Generated by Django 4.2.1 on 2023-08-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0015_rename_masters_send_invitation_serverpermissionsettings_masters_send_invitation_to_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverpermissionsettings',
            name='members_delete_user',
        ),
    ]
