# Generated by Django 4.2.1 on 2023-08-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0016_remove_serverpermissionsettings_members_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': [('delete_user_from_server', 'Can delete user from server'), ('display_private_room_data', 'Can see private room details')]},
        ),
        migrations.AddField(
            model_name='serverpermissionsettings',
            name='masters_can_see_private_rooms',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Forbidden', max_length=20),
        ),
        migrations.AddField(
            model_name='serverpermissionsettings',
            name='members_can_see_private_rooms',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Forbidden', max_length=20),
        ),
        migrations.AddField(
            model_name='serverpermissionsettings',
            name='moderators_can_see_private_rooms',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Forbidden', max_length=20),
        ),
        migrations.AlterField(
            model_name='serverpermissionsettings',
            name='members_create_room',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Forbidden', max_length=20),
        ),
        migrations.AlterField(
            model_name='serverpermissionsettings',
            name='members_delete_messages',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Forbidden', max_length=20),
        ),
        migrations.AlterField(
            model_name='serverpermissionsettings',
            name='moderators_create_room',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Forbidden', max_length=20),
        ),
    ]
