# Generated by Django 4.2.1 on 2023-07-22 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0016_remove_roomjoinnotification_join_request_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomjoinnotification',
            name='invited_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
