# Generated by Django 4.2.1 on 2023-07-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0017_alter_roomjoinnotification_invited_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomJoinNotification',
            new_name='RoomInvite',
        ),
    ]
