# Generated by Django 4.2.1 on 2023-08-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0017_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'permissions': [('create_room_in_server', 'Can create room in server'), ('send_messages_in_server', 'Can send messages in server'), ('delete_masters_from_server', 'Can delete users in master group'), ('delete_moderators_from_server', 'Can delete users in moderators group'), ('delete_members_from_server', 'Can delete users in members group'), ('edit_permissions_in_server', 'Can modify groups permissions'), ('edit_moderators_group', 'Can change moderators group'), ('edit_members_group', 'Can change members group'), ('edit_masters_group', 'Can change masters group')]},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('display_user_profile', 'Can display user informations'), ('change_user_group', 'Can change users group')]},
        ),
        migrations.AddField(
            model_name='serverpermissionsettings',
            name='masters_can_edit_users_group',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Forbidden', max_length=20),
        ),
    ]
