# Generated by Django 4.2.1 on 2023-07-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0019_alter_message_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('delete_chat_message', 'Can delete chat message')]},
        ),
    ]
