# Generated by Django 4.2.1 on 2023-08-05 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0020_remove_user_profile_setttings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissionsettings',
            name='profile_setttings',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_setttings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viperchat.userpermissionsettings'),
        ),
    ]
