# Generated by Django 4.2.1 on 2023-07-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0020_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('delete_message_from_room', 'Can delete message from room')]},
        ),
    ]
