# Generated by Django 4.2.1 on 2023-08-05 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0021_remove_userpermissionsettings_profile_setttings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_setttings',
        ),
        migrations.AddField(
            model_name='userpermissionsettings',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
