# Generated by Django 4.2.1 on 2023-07-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0021_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roominvite',
            options={'permissions': [('invite_user_to_private_room', 'Can send invitations to private room')]},
        ),
    ]
