# Generated by Django 4.2.1 on 2023-07-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0022_alter_roominvite_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roominvite',
            options={'permissions': [('send_invitation', 'Can send invitations to private room')]},
        ),
    ]
