# Generated by Django 4.2.1 on 2023-07-27 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0023_alter_roominvite_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominvite',
            name='room_creator',
        ),
        migrations.AddField(
            model_name='roominvite',
            name='invitation_sender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='invitation_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
