# Generated by Django 4.2.1 on 2023-08-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0024_alter_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(),
        ),
    ]
