# Generated by Django 4.2.1 on 2023-08-06 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0025_alter_room_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('friends_see_profile', 'Friends can see user profile'), ('change_user_group', 'Can change users group'), ('everyone_see_profile', 'Everyone can see user profile')]},
        ),
    ]
