# Generated by Django 4.2.1 on 2023-08-06 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0026_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissionsettings',
            name='everyone_see_your_profile',
        ),
    ]
