# Generated by Django 4.2.1 on 2023-07-28 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0030_alter_message_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
