# Generated by Django 4.2.1 on 2023-07-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0032_alter_message_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('display_user_profile', 'Can display user informations')]},
        ),
    ]
