# Generated by Django 4.2.1 on 2023-07-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0033_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': [('delete_user_from_room', 'Can delete user from room'), ('display_room_data', 'Can see room details')]},
        ),
    ]
