# Generated by Django 4.2.1 on 2023-07-31 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0036_alter_room_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermissionSettings',
            new_name='RoomPermissionSettings',
        ),
    ]
