# Generated by Django 4.2.1 on 2023-07-31 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0038_groupdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupDetail',
        ),
    ]
