# Generated by Django 4.2.1 on 2023-07-31 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viperchat', '0039_delete_groupdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roompermissionsettings',
            old_name='delete_messages',
            new_name='moderators_delete_messages',
        ),
        migrations.RenameField(
            model_name='roompermissionsettings',
            old_name='delete_user',
            new_name='moderators_delete_user',
        ),
    ]
